// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SnapTime.Infrastructure.Data;

#nullable disable

namespace SnapTime.Infrastructure.Migrations
{
    [DbContext(typeof(SnapTimeDbContext))]
    partial class SnapTimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SnapTime.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("SnapTime.Domain.Entities.EvidenceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeuristicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeuristicName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MediaAssetId");

                    b.ToTable("EvidenceEntries");
                });

            modelBuilder.Entity("SnapTime.Domain.Entities.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FileCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FileModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedByHeuristic")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SuggestedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("ScanJobId");

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("SnapTime.Domain.Entities.MetadataEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaAssetId");

                    b.ToTable("MetadataEntries");
                });

            modelBuilder.Entity("SnapTime.Domain.Entities.ScanJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessedFiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScanJobs");
                });

            modelBuilder.Entity("SnapTime.Domain.Entities.EvidenceEntry", b =>
                {
                    b.HasOne("SnapTime.Domain.Entities.MediaAsset", "MediaAsset")
                        .WithMany("EvidenceEntries")
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("SnapTime.Domain.Entities.MediaAsset", b =>
                {
                    b.HasOne("SnapTime.Domain.Entities.ScanJob", "ScanJob")
                        .WithMany("MediaAssets")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("SnapTime.Domain.Entities.MetadataEntry", b =>
                {
                    b.HasOne("SnapTime.Domain.Entities.MediaAsset", "MediaAsset")
                        .WithMany("MetadataEntries")
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("SnapTime.Domain.Entities.MediaAsset", b =>
                {
                    b.Navigation("EvidenceEntries");

                    b.Navigation("MetadataEntries");
                });

            modelBuilder.Entity("SnapTime.Domain.Entities.ScanJob", b =>
                {
                    b.Navigation("MediaAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
